### ISSUE TITLE
Search Page not being themed entirely 

### ISSUE THREAD

**Issue by itokatsu** [ImenaOphelia/yomitan#1]
The popup themeing works great. 
However inside the search page ( _moz-extension:// {yomitan-extension-id} /search.html_ ), the search bar and input field still have their default background.

Thankfully the page pulls the custom CSS so it's as easy as setting `--input-background-color` and maybe some other tweaks that I let you judge of.

Thanks for your work.

**Comment by ImenaOphelia** [comment]
Hi, this should be fixed now! Thank you for contribution.
